### ISSUE TITLE
Ajustements design

### ISSUE THREAD

**Issue by Violenn** [osunyorg/mathieujahnich-master-class#4]
**Menu :**
Garder un espace de 40px entre chaque élément

**Exergues**
exemple sur cette page : https://master-class.mathieujahnich.osuny.site/intervenant-es/mathieu-jahnich/ paragraphe "Mathieu est consultant chercheur..."etc devrait être en Rubik 39px interlignage 120%

**Homepage**
L'etat hover des blocs formations doit être sur fond bleu (voir dans l'onglet System sur le Figma)

**General**
Garder une marge de 100px au dessus du footer

**Page intervenants**
A vérifier avec Mathieu mais s'ils ne sont que 3 on peut utiliser toute la largeur de la grille

merci !

**Comment by arnaudlevy** [comment]
@Clararigaud tu as fait ? Si oui il faut clore l'issue
