### ISSUE TITLE
Pb de couleur

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/mathieujahnich-master-class#5]
https://master-class.mathieujahnich.osuny.site/sessions/2024-06-01-greenwashing-session-pour-les-equipes-communication-et-marketing/

<img width="1792" alt="Capture d’écran 2024-03-16 à 12 11 27" src="https://github.com/noesya/mathieujahnich-master-class/assets/2088968/e0484d54-861a-4c15-afdf-f3d0d7cd9901">

**Comment by Clararigaud** [comment]
done
